// Copies /shared/*.mjs into the card bundle (ESM) and the app functions (CommonJS).
// Run after every edit to /shared:  npm run sync
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const shared = join(root, 'shared');
const targets = {
  esm: join(root, 'src/app/cards/lib'),
  cjs: join(root, 'src/app/functions/lib'),
};
const banner = '// GENERATED by scripts/sync-shared.mjs from /shared. Do not edit here.\n';

export function toEsm(src) {
  return banner + src.replace(/from '\.\/([\w-]+)\.mjs'/g, "from './$1.js'");
}

export function toCjs(src) {
  const names = [];
  let out = src.replace(/import\s*\{([^}]*)\}\s*from\s*'\.\/([\w-]+)\.mjs';/g, (_, list, file) => {
    const ids = list.split(',').map((s) => s.trim()).filter(Boolean).join(', ');
    return `const { ${ids} } = require('./${file}.js');`;
  });
  out = out.replace(/^export (function|const|let|class) ([A-Za-z0-9_$]+)/gm, (_, kind, name) => {
    names.push(name);
    return `${kind} ${name}`;
  });
  if (/^\s*export\s/m.test(out)) throw new Error('Unsupported export form; use `export function` or `export const`.');
  return banner + "'use strict';\n" + out + `\nmodule.exports = { ${names.join(', ')} };\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  for (const dir of Object.values(targets)) mkdirSync(dir, { recursive: true });
  for (const file of readdirSync(shared).filter((f) => f.endsWith('.mjs'))) {
    const src = readFileSync(join(shared, file), 'utf8');
    const base = file.replace(/\.mjs$/, '.js');
    writeFileSync(join(targets.esm, base), toEsm(src));
    writeFileSync(join(targets.cjs, base), toCjs(src));
    console.log(`synced ${file} → cards/lib/${base}, functions/lib/${base}`);
  }
}
