// 1. Copies /shared/*.mjs into the card (ESM, src/app/cards/lib) and the function sources (CommonJS, functions-src/lib).
// 2. Bundles each functions-src/quote-builder-*.js into one self-contained file in src/app/functions/:
//    HubSpot deploys every app function as a single file, so relative requires (./lib/...) don't resolve there.
// Run after every edit to /shared or /functions-src:  npm run sync
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const shared = join(root, 'shared');
const targets = {
  esm: join(root, 'src/app/cards/lib'),
  cjs: join(root, 'functions-src/lib'),
};
const banner = '// GENERATED by scripts/sync-shared.mjs from /shared. Do not edit here.\n';

export function toEsm(src) {
  return banner + src.replace(/from '\.\/([\w-]+)\.mjs'/g, "from './$1.js'");
}

export function toCjs(src) {
  const names = [];
  let out = src.replace(/import\s*\{([^}]*)\}\s*from\s*'\.\/([\w-]+)\.mjs';/g, (_, list, file) => {
    const ids = list.split(',').map((s) => s.trim()).filter(Boolean).join(', ');
    return `const { ${ids} } = require('./${file}.js');`;
  });
  out = out.replace(/^export (function|const|let|class) ([A-Za-z0-9_$]+)/gm, (_, kind, name) => {
    names.push(name);
    return `${kind} ${name}`;
  });
  if (/^\s*export\s/m.test(out)) throw new Error('Unsupported export form; use `export function` or `export const`.');
  return banner + "'use strict';\n" + out + `\nmodule.exports = { ${names.join(', ')} };\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  for (const dir of Object.values(targets)) mkdirSync(dir, { recursive: true });
  for (const file of readdirSync(shared).filter((f) => f.endsWith('.mjs'))) {
    const src = readFileSync(join(shared, file), 'utf8');
    const base = file.replace(/\.mjs$/, '.js');
    writeFileSync(join(targets.esm, base), toEsm(src));
    writeFileSync(join(targets.cjs, base), toCjs(src));
    console.log(`synced ${file} → src/app/cards/lib/${base}, functions-src/lib/${base}`);
  }
  const { buildSync } = await import('esbuild');
  const fnSrc = join(root, 'functions-src');
  for (const file of readdirSync(fnSrc).filter((f) => /^quote-builder-.*\.js$/.test(f))) {
    buildSync({
      entryPoints: [join(fnSrc, file)],
      outfile: join(root, 'src/app/functions', file),
      bundle: true,
      platform: 'node',
      format: 'cjs',
      target: 'node20',
      legalComments: 'none',
      banner: { js: '// GENERATED by scripts/sync-shared.mjs from functions-src/ and /shared. Do not edit here.' },
      logLevel: 'warning',
    });
    console.log(`bundled functions-src/${file} → src/app/functions/${file}`);
  }
}
